version: '3.8'

services:
  web:
    build: .
    command: |
      sh -c "python manage.py migrate --noinput &&
             gunicorn main.wsgi:application --workers=4 --bind=0.0.0.0:8080 --access-logfile -"
    volumes:
      - .:/code
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DEBUG=0
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"
    volumes:
    - ./backup:/backup
    - ../psql_data:/var/lib/postgresql/data
